### ISSUE TITLE
Ipla extractor fails

### ISSUE THREAD

**Issue by jagub2** [haruhi-dl/haruhi-dl#10]
Howdy,
I tried to use haruhi-dl to obtain video but extractor fails. After further investigation, current URL from `get_info` gets 404 response. I suspect Android client has different URLs now and this is the reason of failure.

```
ERROR: An extractor error has occurred. (caused by KeyError('result')); please report this issue on https://haruhi.download/bug . Make sure you are using the latest version; see  https://haruhi.download/update  on how to update. Be sure to call haruhi-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/xx/.local/lib/python3.9/site-packages/haruhi_dl/extractor/common.py", line 549, in extract
    ie_result = self._real_extract(url)
  File "/home/xx/.local/lib/python3.9/site-packages/haruhi_dl/extractor/ipla.py", line 42, in _real_extract
    media = self.get_info(video_id)
  File "/home/xx/.local/lib/python3.9/site-packages/haruhi_dl/extractor/ipla.py", line 83, in get_info
    return res['result']['mediaItem']
KeyError: 'result'
Traceback (most recent call last):
  File "/home/xx/.local/lib/python3.9/site-packages/haruhi_dl/extractor/common.py", line 549, in extract
    ie_result = self._real_extract(url)
  File "/home/xx/.local/lib/python3.9/site-packages/haruhi_dl/extractor/ipla.py", line 42, in _real_extract
    media = self.get_info(video_id)
  File "/home/xx/.local/lib/python3.9/site-packages/haruhi_dl/extractor/ipla.py", line 83, in get_info
    return res['result']['mediaItem']
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xx/.local/lib/python3.9/site-packages/haruhi_dl/HaruhiDL.py", line 827, in wrapper
    return func(self, *args, **kwargs)
  File "/home/xx/.local/lib/python3.9/site-packages/haruhi_dl/HaruhiDL.py", line 848, in __extract_info
    ie_result = ie.extract(url)
  File "/home/xx/.local/lib/python3.9/site-packages/haruhi_dl/extractor/common.py", line 562, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
```

I tried running it on a movie.

Cheers.

**Comment by selfisekai** [comment]
Hi, HTTP 404 would result in an HTTPError thrown. It could be a result of merging Ipla and Cyfrowy Polsat GO into another brand, Polsat Box Go: https://www.ipla.tv/tyrzadzisz
I'm gonna investigate this after work though

**Comment by jagub2** [comment]
As I checked, `get_info` succeeds, it has this stuff in JSON response. I haven't checked whole HTTP request but looks like it returned 200 with invalid JSON.

Exemplary JSON response I got:
`{'error': {'code': 13404, 'message': 'Not found error', 'data': {'type': 'NotFoundException', 'code': 10000, 'message': 'Not found error', 'messageId': 'xxx', 'userMessage': 'Wystąpił błąd (13404:)'}}, 'id': '2137', 'jsonrpc': '2.0'}`

**Comment by selfisekai** [comment]
Apparently series like https://www.ipla.tv/wideo/serial/Miodowe-Lata/5007481/Miodowe-Lata-Mur-czyli-zemsta/6df54484ee2f09a22ff3a8b46c44f328?seasonId=5007481 work correctly, but movies like https://www.ipla.tv/wideo/film/Zemsta/16a03efad5d39239d3e93d9cf15eeb1f do not. This will require some more investigation about the requests made.

**Comment by selfisekai** [comment]
Also TODO: proper error handling

**Comment by selfisekai** [comment]
Root cause identified. Basically Polsat's error handling is a fucking mess, method `getMedia` returns the same error with a much better, non-generic user message:
```json
{
    "error": {
        "code": 13404,
        "data": {
            "code": 10000,
            "message": "Not found error",
            "messageId": "fac44d10-66a5-466d-80a1-792744d3b390",
            "type": "NotFoundException",
            "userMessage": "Materiał jest niedostępny z twojej lokalizacji lub platformy"
        },
        "message": "Not found error"
    },
    "id": "2137",
    "jsonrpc": "2.0"
}
```

This occurs as haruhi-dl states there's no Widevine support from the platform (and there won't be for obvious reasons). The most of Ipla movies require DRM, sadly, but here's a one that doesn't - this works without any code changes: https://www.ipla.tv/wideo/film/Sprawiedliwi-Wydzial-Kryminalny-Wszystko-sie-moze-zdarzyc/189062750c1ce3e2971c7a331c825825

I have added error handling with this error code specifically explaining the problem, to cut off any confusion in the future.
