### ISSUE TITLE
Question about this project

### ISSUE THREAD

**Issue by jeanslack** [haruhi-dl/haruhi-dl#13]
Hello,

Is this project still maintained? 
Since I really approve of the license type and since it offers good features I was thinking of including it in my [GUI](https://github.com/jeanslack/Videomass). 

Regards

**Comment by selfisekai** [comment]
we're mostly focused on other projects now, but we'll still maintain this code if there are any problems

**Comment by jeanslack** [comment]
@selfisekai 

Thanks for the quick response.

Currently youtube-dl seems to have been abandoned for months, and haruhi-dl hasn't released since June, it also has the same slow downloading issue as youtube-dl, so I asked this question.
