### ISSUE TITLE
[Niezwiązane z haruhi-dl] Problem z logowaniem na wasz GitLab

### ISSUE THREAD

**Issue by micwoj92** [haruhi-dl/haruhi-dl#2]
Dzień dobry, dzisiaj chciałem założyć konto na waszym GitLabie. Najpierw spróbowałem przez konto GitHub, wynik to "blocked user" jak możecie zobaczyć tutaj https://git.sakamoto.pl/micwoj92. No to pomyślałem sobie, że założę przez e-maila no ale też się nie udało. Pojawia się błąd `Invalid Login or password.` pomimo wpisania prawidłowych danych logowania. Wiem, że do śledzenia "ticketów" wystarczy https://git.sakamoto.pl/laudompat/haruhi-dl/-/issues.atom ale wolałbym dostawać powiadomienia na emaila i tylko o tych ticketach, które mnie interesują.

**Comment by selfisekai** [comment]
To nasza prywatna instancja GitLaba, narazie nie przyjmujemy innych użytkowników, bo nie jesteśmy na to jeszcze gotowe. Issue i merge requesty będą na GitLaba przenoszone przez [Copykitku](https://git.sakamoto.pl/laudompat/copykitku). Poza tym czekamy z nadzieją na standard [ForgeFed](https://forgefed.peers.community) i jego implementację w GitLabie.

**Comment by micwoj92** [comment]
Ah, w sumie tak podejrzewałem, bo strona rejestrowania jest ukryta. Można zamykać? A, i jeszcze jedno, czy jeśli rejestracja będzie publiczna, byłaby możliwość odblokowania konta "micwoj92" na waszej instancji?

**Comment by selfisekai** [comment]
Oczywiście, będzie.
