### ISSUE TITLE
Chocolatey

### ISSUE THREAD

**Issue by Mennaruuk** [haruhi-dl/haruhi-dl#3]
Hi! Are there any plans to submit haruhi-dl to Chocolatey? I think that'd be terrific if it can happen!

**Comment by ptrcnull** [comment]
I guess we can try to make that happen, I don't know if haruhi-dl has a working Windows build pipeline though.

**Comment by selfisekai** [comment]
[The Windows binary build script](https://git.sakamoto.pl/laudompat/haruhi-dl/-/blob/master/devscripts/wine-py2exe.sh) from the ytdl repository uses python 2.7, which we have dropped, so we would have to upgrade the py2exe version. That would probably break the binary patches, which ytdl is applying to make it work on Wine. It seems like the Wine issue has been [fixed](https://bugs.winehq.org/show_bug.cgi?id=3591) a week ago, but we will have to wait for the next Wine 6.x release for that improvement to be shipped.

**Comment by selfisekai** [comment]
Got a working (tested with just Wine yet) .exe file with Python 3.8.8. I'll test that on actual Windows machines and try to insert Playwright into that somehow, but even if I somehow succeed, this will of course be optional (Playwright and non-Playwright binaries).

**Comment by Mennaruuk** [comment]
Thank you!!!!! Can you say more about what Playwright can do for haruhi-dl? It sounds exciting!

**Comment by selfisekai** [comment]
[Playwright](https://playwright.dev/) is required by some extractors, which we couldn't manage to create in a normal way (namely: TikTok user profiles), so instead hdl automates a web browser open in the background to fetch the wanted content. That's the ultimate approach, which we use only if all others fail.

**Comment by Mennaruuk** [comment]
That is so cool! I can see how it’s more of a fallback method, but I still like how it does it. Sounds like a successor to Selenium. Thanks for implementing Playwright!
