### ISSUE TITLE
haruhi-dl: command not found

### ISSUE THREAD

**Issue by Mennaruuk** [haruhi-dl/haruhi-dl#5]
On Ubuntu 20.04, after installing haruhi-dl using pip3, I get the following error:
"haruhi-dl: command not found."

How can I fix this dreadful error? Also shows up when I install youtube-dl.

**Comment by selfisekai** [comment]
I guess it has been installed to your user-specific directory (`~/.local/bin/`), but it's not in the PATH variable.

Try one of these ways:
1. Install with `sudo pip3 install haruhi-dl` (system-wide)
2. Add this line to your `~/.bashrc` (or `~/.zshrc` if you're using zsh):
```sh
export PATH="$PATH:$HOME/.local/bin"
```

**Comment by Mennaruuk** [comment]
Now it works well. Thank you!!!
